### ISSUE TITLE
Support for oAuth

### ISSUE THREAD

**Issue by edknittel** [24u/fmRESTor.php#1]
It does not look like it's possible to use fmRESTor with an oAuthRequestId and oAuthIdentifier for authentication. Unless I'm missing something, any time you access the fmRESTor class you must pass in the username and password. Using https://github.com/ClickWorks/FMDataAPIOAuthConnector I am able to authenticate using oAuth but once I receive the token in the response I don't see how to use it with fmRESTor.

**Comment by filip24u** [comment]
Hello edknittel,

First of all, I would like to apologize for the late reply.

I am sorry, but at the moment, fmRESTor does not have an implemented function for logging in via oAuth.

I'am really appreciate for letting me know about this missing feature. 

I will most likely include this missing feature in development for future versions.

Have a nice day,
Filip
