### ISSUE TITLE
Typo in fmDateSource

### ISSUE THREAD

**Issue by micah-woods** [24u/fmRESTor.php#2]
Hello HOnza,

Pretty sure there's a typo, 'fmDateSource' is referenced 4 times and I think it was meant to be 'fmDataSource'. Code works fine but is a little confusing.

-- Micah

**Comment by filip24u** [comment]
Hello Micah,

Thank you for reporting the bug, I really appreciate it. I'm sorry for the late reply. I'll look into it and make bugfix in following days. I'll let you know.

Have a nice day,
Filip

**Comment by filip24u** [comment]
Hello Micah, 

I would like to inform you, that this bug have been fixed in version 19.0.3.

Thank you,
Have a nice day,
Filip
