### ISSUE TITLE
Sort order issue in example

### ISSUE THREAD

**Issue by mbcbus** [24u/fmRESTor.php#4]
https://github.com/24u/fmRESTor.php/blob/a3ede290cfe358c7295ae5e682ce99ca54a0a4ce/demo/findRecord.php#L20

This shows something like this on line 20:
`"surname" => "Neal", "sortOrder" => "ascend"`

It looks like a find request in sort order. I think it should be something like:
`"fieldName" => "surname", "sortOrder" => "ascend"`

Hope this helps.

**Comment by filip24u** [comment]
Hello,

Thank you for letting us know. We appreciate it. Yes definitly, it should be like you are writing. We will fix that in the new version of fmRESTor.

Thank you and have a nice day,
Filip
