### ISSUE TITLE
Errors after updating to FMS 19.4.2

### ISSUE THREAD

**Issue by mbcbus** [24u/fmRESTor.php#5]
All requests utilizing fmRESTor are returning this error message after a recent update to FMS 19.4.2.
This update included the manual installation of PHP on that server to run webhook scripts. This install followed Claris's official guide: https://support.claris.com/s/article/PHP-bundling-deprecation-and-removal-from-FileMaker-Server?language=en_US 

`HTTP/2 stream 0 was not closed cleanly: Unknown error code (err 1)`

Research shows that you need to force cURL to use HTTP 1:
`curl_setopt($curl, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);`

However, since fmRESTor is bundled, there should be a setting to allow toggle of this.

Perhaps something like:
`$options = array(
    "sessionName" => "fm-api-token",
    "tokenExpireTime" => 5,
    "allowInsecure" => true,
    "http" => 1.1
);

$fm = new fmRESTor("127.0.0.1", "DB", "layout", "user", "pass", $options);`

**Comment by filip24u** [comment]
Hello,

Thank you for letting us know. We appreciate it. Actually, there is method how this can be handled by (without changing code inside fmRESTor):

        $this->fm = new fmRESTor($config["host"], $config["database"], self::LAYOUT, $config["username"], $config["password"], [
        	"autorelogin" => true,
            "allowInsecure" => true,
            "curlOptions" => [
                CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1
            ],
        );
        
But definitly we will added into documentation, because this could be helpful for more other users.

Thank you !
Filip
